NEIGHBORHOODS = {
    "Complexul Studentesc": {
        "city": "Timisoara",
        "aliases": [
            "complexul studentesc",
            "complex studentesc",
            "zona studenteasca",
        ],
        "centroid": [45.7476, 21.2331],
    },
    "Aradului": {
        "city": "Timisoara",
        "aliases": [
            "aradului",
            "aradului est",
            "zona aradului",
            "calea aradului",
            "aradului west",
            "jabri nord residence",
            "jabri nord", 
            "jabri residence",
        ],
        "centroid": [45.7808, 21.2095],
    },
    "Sagului": {
        "city": "Timisoara",
        "aliases": [
            "sagului",
            "zona sagului",
            "calea sagului",
            "shopping city mall",
            "strada iris",
            "piata doina",
            "zona doina",
            "zona kiriac",
            "kiriac",
        ],
        "centroid": [45.7262, 21.2054],
    },
    "Torontalului": {
        "city": "Timisoara",
        "aliases": [
            "torontalului",
            "zona torontalului",
            "calea torontalului",
        ],
        "centroid": [45.7796, 21.1914],
    },
    "Buziasului": {
        "city": "Timisoara",
        "aliases": [
            "buziasului",
            "zona buziasului",
            "calea buziasului",
            "zona aem",
            "aem",
        ],
        "centroid": [45.7335, 21.2574],
    },
    "Bucovina": {
        "city": "Timisoara",
        "aliases": ["bucovina", "zona bucovina","cartier bucovina"],
        "centroid": [45.1218, 21.3294],
    },
    "Kuncz": {
        "city": "Timisoara",
        "aliases": ["kuncz", "zona kuncz","cartier kuncz"],
        "centroid": [45.2213, 21.4213],
    },
    "Lipovei": {
        "city": "Timisoara",
        "aliases": ["lipovei",
                    "zona lipovei",
                    "cartier lipovei",
                    "strada stuparilor"],
        "centroid": [45.7739, 21.2445],
    },
    "Soarelui": {
        "city": "Timisoara",
        "aliases": ["soarelui", "zona soarelui", "zona spitalul judetean",],
        "centroid": [45.7346, 21.2482],
    },
    "Girocului": {
        "city": "Timisoara",
        "aliases": ["girocului", "zona girocului","martirilor"],
        "centroid": [45.7318, 21.2294],
    },
    "Circumvalatiunii": {
        "city": "Timisoara",
        "aliases": [
        "circumvalatiunii",
        "zona circumvalatiunii", 
        "City of Mara",
        ],
        "centroid": [45.7644, 21.2089],
    },
    "Chisoda": {
        "city": "Timisoara",
        "aliases": ["chisoda", "zona chisoda"],
        "centroid": [45.7318, 21.2294],
    },
    "Urseni": {
    "city": "Timisoara",
    "aliases": [
        "urseni",
        "zona urseni",
    ],
    "centroid": [45.7085, 21.2735],
    },
    "Iosefin": {
        "city": "Timisoara",
        "aliases": ["iosefin",
                    "zona garii",
                    "zona gara de nord",
                    "zona maria",
                    "piata maria",
                    "zona sinaia",
                    "nicolaie titulescu",
                    "n. titulescu",
                    "sp.n. titulescu"],
        "centroid": [45.7462, 21.1973],
    },
    "Iulius Town": {
    "city": "Timisoara",
    "aliases": [
        "iulius town",
        "iulius mall",
        "iulius mall town",
    ],
    "centroid": [45.7669, 21.2414],
    },
    "Elisabetin": {
        "city": "Timisoara",
        "aliases": ["elisabetin",
                    "zona elisabetin",
                    "cartier elisabetin",
                    "zona balcescu",
                    "balcescu",
                    "zona constantin brancoveanu",
                    "brancoveanu",
                    "zona odobescu"],
        "centroid": [45.7441, 21.2145],
    },
    "Dacia": {
        "city": "Timisoara",
        "aliases": ["dacia", "zona dacia", "cartier dacia"],
        "centroid": [45.7702, 21.2292],
    },
    "Fabric": {
        "city": "Timisoara",
        "aliases": ["fabric",
                    "zona fabric",
                    "cartier fabric",
                    "umt",
                    "zona umt",
                    "zona traian",
                    "piata traian"],
        "centroid": [45.7564, 21.2434],
    },
    "Fratelia": {
        "city": "Timisoara",
        "aliases": ["fratelia", "zona fratelia", "cartier fratelia"],
        "centroid": [45.7318, 21.2294],
    },
    "Freidorf": {
        "city": "Timisoara",
        "aliases": ["freidorf", "zona freidorf", "cartier freidorf"],
        "centroid": [45.7198, 21.1776],
    },
    "Dambovita": {
        "city": "Timisoara",
        "aliases": [
            "dambovita",
            "zona dambovita",
            "cartier dambovita",
        ],
        "centroid": [45.7334, 21.1986],
    },
    "Tipografilor": {
        "city": "Timisoara",
        "aliases": ["tipografilor", "zona tipografilor", "Badea Cartan", "take ionescu"],
        "centroid": [45.7668, 21.2388],
    },
    "Braytim": {
        "city": "Timisoara",
        "aliases": ["braytim", "zona braytim", "cartier braytim"],
        "centroid": [45.7199, 21.2387],
    },
    "Steaua": {
        "city": "Timisoara",
        "aliases": ["steaua", "zona steaua", "cartier steaua"],
        "centroid": [45.7284, 21.2117],
    },
    "Cetatii": {
        "city": "Timisoara",
        "aliases": ["cetatii",
                    "zona cetatii",
                    "cartier cetatii",
                    "zona cetate",
                    "cetate",
                    "zona piata marasti",
                    "zona piata victoriei",
                    "zona unirii",
                    "piata unirii"],
        "centroid": [45.7687, 21.1985],
    },
    "Ciarda Rosie": {
        "city": "Timisoara",
        "aliases": ["ciarda rosie", "zona ciarda rosie", "ciarda-rosie", "cartier ciarda rosie"],
        "centroid": [45.7318, 21.2294],
    },
    "Telegrafului": {
        "city": "Timisoara",
        "aliases": ["telegrafului", "zona telegrafului", "simion barnutiu"],
        "centroid": [45.7318, 21.2294],
    },
    "Mehala":{
        "city": "Timisoara",
        "aliases":["mehala", "zona mehala", "cartier mehala"],
        "centroid":[45.9312, 21.5342],
    },
    "Lunei": {
        "city": "Timisoara",
        "aliases": ["lunei", "zona lunei","cartier lunei", "zona printul turcesc", "cartier printul turcesc"],
        "centroid": [45.7318, 21.2294],
    },
    "Modern":{
        "city": "Timisoara",
        "aliases": ["in modern", "zona modern", "cartier modern","dorobantilor"],
        "centroid": [45.6923, 21.3411],
    },
    "Ronat": {
        "city": "Timisoara",
        "aliases": ["ronat", "zona ronat", "cartier ronat"],
        "centroid": [45.7318, 21.2294],
    },
    "Blascovici": {
        "city": "Timisoara",
        "aliases": ["blascovici", "zona blascovici", "cartier blascovici"],
        "centroid": [45.7234, 21.2300],
    },
    "Olimpia": {
        "city": "Timisoara",
        "aliases": ["zona olimpia", "olimpia"],
        "centroid": [45.7456, 21.2356],
    },
    "Plopi": {
        "city": "Timisoara",
        "aliases": ["plopi", "zona plopi", "cartier plopi"],
        "centroid": [45.7318, 21.2294],
    },
    "Crisan": {
        "city": "Timisoara",
        "aliases": ["crisan", "zona crisan", "cartier crisan"],
        "centroid": [45.7318, 21.2294],
    },
    "Ghiroda": {
        "city": "Timisoara",
        "aliases": ["ghiroda", "zona ghiroda", "ghiroda noua", "ghiroda veche","zona aeroport", "aeroport"],
        "centroid": [45.7318, 21.2294],
    },
    "Dumbravita": {
        "city": "Dumbravita",
        "aliases": ["dumbravita", "zona dumbravita", "comuna dumbravita", "cartier dumbravita"],
        "centroid": [45.8012, 21.2424],
    },
    "Giroc": {
        "city": "Giroc",
        "aliases": ["giroc", "calea urseni"],
        "centroid": [45.6948, 21.2358],
    },
    "Giarmata-Vii": {
        "city": "Timisoara",
        "aliases": ["giarmata-vii", "giarmata vi"],
        "centroid": [45.7318, 21.2294],
    },
    "Mosnita Noua": {
        "city": "Mosnita Noua",
        "aliases": ["mosnita noua", "zona mosnita noua"],
        "centroid": [45.7228, 21.3254],
    },
    "Mosnita Veche":{
        "city": "Mosnita Veche",
        "aliases": ["mosnita veche", "zona mosnita veche"],
        "centroid": [45.7200, 21.3333],
    },
}
